{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Mon Nov  9 03:33:27 2015) by ROOT version5.34/18
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(0,0,1,1);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.15);
   c1_n2->SetRightMargin(0.15);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.15);
   c1_n2->SetFrameFillStyle(0);
   c1_n2->SetFrameBorderMode(0);
   
   TH1D *SelDiParton_DEta = new TH1D("SelDiParton_DEta","SelDiParton_DEta",50,0,10);
   SelDiParton_DEta->SetBinContent(1,6);
   SelDiParton_DEta->SetBinContent(2,3);
   SelDiParton_DEta->SetBinContent(3,2);
   SelDiParton_DEta->SetBinContent(4,3);
   SelDiParton_DEta->SetBinContent(5,4);
   SelDiParton_DEta->SetBinContent(6,7);
   SelDiParton_DEta->SetBinContent(7,11);
   SelDiParton_DEta->SetBinContent(8,7);
   SelDiParton_DEta->SetBinContent(9,7);
   SelDiParton_DEta->SetBinContent(10,18);
   SelDiParton_DEta->SetBinContent(11,12);
   SelDiParton_DEta->SetBinContent(12,20);
   SelDiParton_DEta->SetBinContent(13,31);
   SelDiParton_DEta->SetBinContent(14,42);
   SelDiParton_DEta->SetBinContent(15,41);
   SelDiParton_DEta->SetBinContent(16,42);
   SelDiParton_DEta->SetBinContent(17,73);
   SelDiParton_DEta->SetBinContent(18,87);
   SelDiParton_DEta->SetBinContent(19,110);
   SelDiParton_DEta->SetBinContent(20,154);
   SelDiParton_DEta->SetBinContent(21,197);
   SelDiParton_DEta->SetBinContent(22,278);
   SelDiParton_DEta->SetBinContent(23,363);
   SelDiParton_DEta->SetBinContent(24,450);
   SelDiParton_DEta->SetBinContent(25,576);
   SelDiParton_DEta->SetBinContent(26,810);
   SelDiParton_DEta->SetBinContent(27,1136);
   SelDiParton_DEta->SetBinContent(28,1346);
   SelDiParton_DEta->SetBinContent(29,1770);
   SelDiParton_DEta->SetBinContent(30,2259);
   SelDiParton_DEta->SetBinContent(31,2756);
   SelDiParton_DEta->SetBinContent(32,3368);
   SelDiParton_DEta->SetBinContent(33,3442);
   SelDiParton_DEta->SetBinContent(34,2906);
   SelDiParton_DEta->SetBinContent(35,2220);
   SelDiParton_DEta->SetBinContent(36,1724);
   SelDiParton_DEta->SetBinContent(37,1314);
   SelDiParton_DEta->SetBinContent(38,912);
   SelDiParton_DEta->SetBinContent(39,725);
   SelDiParton_DEta->SetBinContent(40,481);
   SelDiParton_DEta->SetBinContent(41,338);
   SelDiParton_DEta->SetBinContent(42,251);
   SelDiParton_DEta->SetBinContent(43,153);
   SelDiParton_DEta->SetBinContent(44,102);
   SelDiParton_DEta->SetBinContent(45,78);
   SelDiParton_DEta->SetBinContent(46,35);
   SelDiParton_DEta->SetBinContent(47,18);
   SelDiParton_DEta->SetBinContent(48,9);
   SelDiParton_DEta->SetBinContent(49,1);
   SelDiParton_DEta->SetBinContent(50,1);
   SelDiParton_DEta->SetEntries(30699);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   SelDiParton_DEta->SetLineColor(ci);
   SelDiParton_DEta->GetXaxis()->SetTitle("Selected Diparton - #Delta#eta");
   SelDiParton_DEta->GetXaxis()->SetRange(1,100);
   SelDiParton_DEta->GetXaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetXaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetXaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetXaxis()->SetTitleFont(42);
   SelDiParton_DEta->GetYaxis()->SetTitle("Number of events");
   SelDiParton_DEta->GetYaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetYaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetYaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetYaxis()->SetTitleOffset(1.75);
   SelDiParton_DEta->GetYaxis()->SetTitleFont(42);
   SelDiParton_DEta->GetZaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetZaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetZaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetZaxis()->SetTitleFont(42);
   SelDiParton_DEta->Draw("");
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
